services:
#    fos_rest.example:
#        class: FOS\RestBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    fos_rest.service.serializer:
        class: FOS\RestBundle\FOSRestBundle
        param_fetcher_listener: true
        body_listener: true
        format_listener: true
        view:
            view_response_listener: 'force'
        routing_loader:
            default_format: json
